<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="<?php echo $ENCODING; ?>" />
        <title>RP</title>
        <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" />
        <script src="/js/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
    </head>
    <body>
        <font face="Arial">
        <div class="container col-xs-12 col-sm-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand">RaidPlaner</a>
                    </div>
                    
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li><a href="/">Home <span class="sr-only">(current)</span></a></li>
                            <?php if(\Base::instance()->get('SESSION.user')) : ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Character <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/character/create">Create</a></li>
                                    <li><a href="/character/list">List</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Raid <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <?php if(\Base::instance()->get('SESSION.user.raidleader')) : ?>
                                    <li><a href="/raid/create">Create</a></li>
                                    <?php endif ?>
                                    <li><a href="/raid/list">List</a></li>
                                </ul>
                            </li>      
                            <?php if(\Base::instance()->get('SESSION.user.admin')) : ?>                            
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/user/list">Userlist</a></li>
                                </ul>
                            </li>     
                            <?php endif ?>
                            <?php else : ?>
                            <li><a href="/user/create">Register User <span class="sr-only">(current)</span></a></li>
                            <?php endif ?>
                        </ul>
                            
                        <?php if(\Base::instance()->get('SESSION.user')) : ?>
                        <div class="btn-group navbar-btn navbar-right">
                            <button type="button" class="btn btn-default"><?php echo \Base::instance()->get('SESSION.user.email') ?></button>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <span class="caret"></span>
                              <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                              <li><a href="/user/edit/<?php echo \Base::instance()->get('SESSION.user.id') ?>">Edit</a></li>
                              <li><a href="/logout">Logout</a></li>
                            </ul>
                        </div>
                        <?php else : ?>
                        <a type="button" href="/auth" class="btn btn-default navbar-btn navbar-right">Login</a> 
                        <?php endif ?>
                    </div>
                    
                </div>
            </nav>
            
            <h1>
                <?php echo \Base::instance()->get('headTitle'); ?>
                <small><?php echo \Base::instance()->get('headSubTitle'); ?></small>
            </h1>
            
            <?php echo $this->render(Base::instance()->get('content')); ?>
        </div>
        </font>
    </body>
</html>