<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="<?php echo $ENCODING; ?>" />
        <title>RaidPlaner</title>
        <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css" />
        <link rel="stylesheet" href="/css/calendar.min.css" type="text/css" />
        <script src="/js/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/underscore.min.js"></script>
        <script src="/js/language/de-DE.js"></script>
        <script src="/js/calendar.min.js"></script>
    </head>
    <body>
        <font face="Arial">
        <div class="container col-xs-12 col-sm-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand">RaidPlaner</a>
                    </div>
                    
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li><a href="/">Home <span class="sr-only">(current)</span></a></li>
                            <?php if(\Base::instance()->get('SESSION.user')) : ?>
                            <li><a href="/calendar">Kalender <span class="sr-only">(current)</span></a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Charakter <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/character/create">Erstellen</a></li>
                                    <li><a href="/character/list">Liste</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Raid <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <?php if(\Base::instance()->get('SESSION.user.raidleader')) : ?>
                                    <li><a href="/raid/create">Erstellen</a></li>
                                    <?php endif ?>
                                    <li><a href="/raid/list">Liste</a></li>
                                </ul>
                            </li>      
                            <?php if(\Base::instance()->get('SESSION.user.admin')) : ?>                            
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/user/list">Benutzerliste</a></li>
                                </ul>
                            </li>     
                            <?php endif ?>
                            <?php else : ?>
                            <li><a href="/user/create">Benutzer registrieren <span class="sr-only">(current)</span></a></li>
                            <?php endif ?>
                        </ul>
                            
                        <?php if(\Base::instance()->get('SESSION.user')) : ?>
                        <div class="btn-group navbar-btn navbar-right">
                            <button type="button" class="btn btn-default"><?php echo \Base::instance()->get('SESSION.user.email') ?></button>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <span class="caret"></span>
                              <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                              <li><a href="/user/edit/<?php echo \Base::instance()->get('SESSION.user.id') ?>">Anpassen</a></li>
                              <li><a href="/auth/logout">Logout</a></li>
                            </ul>
                        </div>
                        <?php else : ?>
                        <a type="button" href="/auth" class="btn btn-default navbar-btn navbar-right">Login</a> 
                        <?php endif ?>
                    </div>
                    
                </div>
            </nav>
            
            <h1>
                <?php echo \Base::instance()->get('headTitle'); ?>
                <small><?php echo \Base::instance()->get('headSubTitle'); ?></small>
            </h1>
            
            <?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
            <div class="alert alert-danger">
                <i class="glyphicon glyphicon-exclamation-sign"></i><strong>Error!</strong><br>
                <?php 
                    echo \Base::instance()->get('SESSION.errormsg');
                    \Base::instance()->clear('SESSION.errormsg');
                ?>
            </div>
            <?php endif ?>
            <?php if (\Base::instance()->get('SESSION.successmsg') != "") : ?>
            <div class="alert alert-success">
                <i class="glyphicon glyphicon-ok"></i> <strong>OK!</strong><br>
                <?php 
                    echo \Base::instance()->get('SESSION.successmsg');
                    \Base::instance()->clear('SESSION.successmsg');
                ?>
            </div>
            <?php endif ?>            
            
            <?php echo $this->render(Base::instance()->get('content')); ?>
            
            <?php if (is_array(\Base::instance()->get('SESSION.failedFields'))) : ?>
            <script>
                <?php foreach (\Base::instance()->get('SESSION.failedFields') as $fieldname) : ?>
                $("#<?php echo $fieldname ?>").parent().addClass('has-error');
                <?php endforeach; ?>
                <?php \Base::instance()->clear('SESSION.failedFields'); ?>
            </script>
            <?php endif ?>            
        </div>
        </font>
    </body>
</html>