<?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
<div class="alert alert-danger">
    <i class="glyphicon glyphicon-exclamation-sign"></i><strong>Error!</strong><br>
    <?php 
        echo \Base::instance()->get('SESSION.errormsg');
        \Base::instance()->clear('SESSION.errormsg');
    ?>
</div>
<?php endif ?>
<?php if (\Base::instance()->get('SESSION.successmsg') != "") : ?>
<div class="alert alert-success">
    <i class="glyphicon glyphicon-ok"></i> <strong>OK!</strong><br>
    <?php 
        echo \Base::instance()->get('SESSION.successmsg');
        \Base::instance()->clear('SESSION.successmsg');
    ?>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == "list") : ?>
<div class="table-responsive">
<table class="table table-bordered table-hover table-condensed table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>EMail</th>
            <th>Characters</th>
            <th>Mailvalidation</th>
            <th>Raidleader</th>
            <th>Admin</th>
            <th></th>
        </tr>
    </thead>
    
    <tbody>
<?php foreach (\Base::instance()->get('users') as $user):?>
    <tr>
        <td><?php echo $user->id ?></td>
        <td><?php echo $user->email ?></td>
        <td>
            <ul>
        <?php foreach(\Base::instance()->get('characters') as $character) : ?>
            <?php if($character->userid == $user->id) : ?>
                <li><?php echo $character->name ?></li>
            <?php endif ?>
        <?php endforeach ?>
            </ul>                
        </td>
        <?php if($user->mailvalidation) : ?>
        <td><i class="glyphicon glyphicon-remove"></i></td>  
        <?php else : ?>
        <td><i class="glyphicon glyphicon-ok"></i></td> 
        <?php endif ?>
        <?php if($user->raidleader) : ?>
        <td><i class="glyphicon glyphicon-ok"></i></td>  
        <?php else : ?>
        <td><i class="glyphicon glyphicon-remove"></i></td> 
        <?php endif ?> 
        <?php if($user->admin) : ?>
        <td><i class="glyphicon glyphicon-ok"></i></td>  
        <?php else : ?>
        <td><i class="glyphicon glyphicon-remove"></i></td> 
        <?php endif ?>          
        <td>
            <a class="btn btn-warning btn-sm" href="/user/edit/<?php echo $user->id ?>" role="button">
                <i class="glyphicon glyphicon-pencil"></i> Edit
            </a>
            <a class="btn btn-danger btn-sm" href="/user/delete/<?php echo $user->id ?>" role="button">
                <i class="glyphicon glyphicon-remove"></i> Delete
            </a>
        </td>      
    </tr>
<?php endforeach;?>   
    </tbody>
    
    <tfoot>
        <tr>
            <td colspan="6">&nbsp;</td>
        </tr>
    </tfoot>
</table>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == "create") : ?>
<div class="well bs-component col-md-4 col-lg-4">
    <legend>User Registration</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <div class="form-group">
            <label for="email" class="control-label">EMail</label> 

            <input type="email" name="email" id="email" placeholder="user@example.com" class="form-control"> 
        </div>  
        
        <div class="form-group">
            <label for="password" class="control-label">Password</label> 

            <input type="password" name="password" id="password" placeholder="Password" class="form-control" required>        
        </div>    
        
        <div class="form-group">
            <label for="password2" class="control-label">Confirm Password</label> 

            <input type="password" name="password2" id="password2" placeholder="Confirm Password" class="form-control" required>        
        </div>         

        <input type="submit" name="submit" class="btn btn-primary" value="Register"> 
    </form>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == "edit") : ?>
<div class="well bs-component col-md-4 col-lg-4">
    <legend>Edit User</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <input type="hidden" name="id" value="<?php echo \Base::instance()->get('user')->id ?>">
        
        <div class="form-group">
            <label for="email" class="control-label">EMail</label> 

            <input type="text" name="email" id="name" value="<?php echo \Base::instance()->get('user')->email ?>" class="form-control" readonly>        
        </div>    
        
        <div class="form-group">
            <label for="password" class="control-label">Password</label>    

            <input type="password" name="password" id="password" placeholder="New Password" class="form-control"> 
        </div>          

        <div class="form-group">
            <label for="password2" class="control-label">Confirm Password</label>    

            <input type="password" name="password2" id="password2" placeholder="Confirm new Password" class="form-control"> 
        </div>       

        <input type="submit" name="submit" class="btn btn-primary" value="Submit"> 
    </form>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == "delete") : ?>
<p>Delete User <?php echo \Base::instance()->get('user')->email ?> and the following Characters?</p>
<ul>
    <?php foreach (\Base::instance()->get('characters') as $character) : ?>
    <li><?php echo $character->name ?></li>
    <?php endforeach ?>
</ul>

<form action=""  method="POST" enctype="multipart/form-data">
    <input type="submit" name="submit" class="btn btn-danger" value="Delete">
    <a class="btn btn-primary" href="/user/list" role="button">Back</a>
</form>
<?php endif ?>

<?php if (is_array(\Base::instance()->get('SESSION.failedFields'))) : ?>
<script>
    <?php foreach (\Base::instance()->get('SESSION.failedFields') as $fieldname) : ?>
    $("#<?php echo $fieldname ?>").parent().addClass('has-error');
    <?php endforeach; ?>
    <?php \Base::instance()->clear('SESSION.failedFields'); ?>
</script>
<?php endif ?>
    