<?php $f3 = \Base::instance() ?>

<div id="page-header" class="row">
    <div class="col-md-4 col-lg-4 text-left">
        <h3></h3>
    </div>
    <div class="col-md-4 col-lg-4 col-md-offset-4 col-lg-offset-4 text-right">
        <div class="btn-group" role="group">
                <button class="btn btn-primary" data-calendar-nav="prev"><i class="glyphicon glyphicon-chevron-left"></i></button>
                <button class="btn" data-calendar-nav="today">Heute</button>
                <button class="btn btn-primary" data-calendar-nav="next"><i class="glyphicon glyphicon-chevron-right"></i></button>
        </div>        
    </div>
</div>

<div id="calendar"></div>    

<script type="text/javascript">
    $('.btn-group button[data-calendar-nav]').each(function() {
            var $this = $(this);
            $this.click(function() {
                    calendar.navigate($this.data('calendar-nav'));
            });
    });    
    
    var calendar = $("#calendar").calendar({
            language: 'de-DE',
            tmpl_path: '/tmpls/',
            events_source: '/api/raid/getraids',
            onAfterViewLoad: function(view) {
                $('#page-header h3').text(this.getTitle());
            },
        });         
</script>
