<?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
<div class="alert alert-danger">
    <i class="glyphicon glyphicon-exclamation-sign"></i>
    <?php 
        echo \Base::instance()->get('SESSION.errormsg');
        \Base::instance()->clear('SESSION.errormsg');
    ?>
</div>
<?php endif ?>
<?php if (\Base::instance()->get('SESSION.successmsg') != "") : ?>
<div class="alert alert-success">
    <i class="glyphicon glyphicon-ok"></i> <strong>OK!</strong><br>
    <?php 
        echo \Base::instance()->get('SESSION.successmsg');
        \Base::instance()->clear('SESSION.successmsg');
    ?>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == 'list') : ?>
<div class="table-responsive">
<table class="table table-bordered table-hover table-condensed table-striped">
    <thead>
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>Spieler</th>
            <th>Schwierigkeit</th>
            <th>RW</th>
            <th>Zeitpunkt</th>
            <?php if (\Base::instance()->get('SESSION.user.raidleader')) : ?>
            <th></th>
            <?php endif ?>
        </tr>
    </thead>
    
    <tbody>
<?php foreach (\Base::instance()->get('raidlist') as $raid):?>
    <tr id="<?php echo $raid->id ?>">
        <td><?php echo $raid->id ?></td>
        <td><?php echo $raid->name ?></td>
        <td><?php echo $raid->players ?></td>     
        <td><?php echo $raid->difficulty ?></td>   
        <td><?php echo $raid->armorclass ?></td>    
        <td><?php echo date("d.m.Y H:i", strtotime($raid->datetime)) ?></td> 
        <?php if (\Base::instance()->get('SESSION.user.raidleader')) : ?>
        <td>
            <a class="btn btn-warning btn-sm" href="/raid/edit/<?php echo $raid->id ?>" role="button">
                <i class="glyphicon glyphicon-pencil"></i> Edit
            </a>
            <a class="btn btn-danger btn-sm" href="/raid/delete/<?php echo $raid->id ?>" role="button">
                <i class="glyphicon glyphicon-remove"></i> Delete
            </a>
        </td> 
        <?php endif ?>
    </tr>
<?php endforeach;?>   
    </tbody>
    
    <tfoot>
        <tr>
            <td colspan="6">&nbsp;</td>
        </tr>
    </tfoot>
</table>
</div>

<script>
    $('tr').click(function() {
        var href = "/raid/show/" + $(this).attr("id");
        if(href) {
            window.location = href;
        }
    });
</script>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == 'show') : ?>
<div class="table-responsive">
<table class="table table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Kommentar</th>
            <th>Teilnahme</th>
        </tr>
    </thead>
    
    <tbody>
<?php foreach (\Base::instance()->get('registrations') as $registration):?>
    <?php if ($registration->participation === 0) : ?>
    <tr class="danger">
        <td><?php echo ++$i ?></td>
        <td><?php echo $registration->charactername ?></td>
        <td><?php echo $registration->comment ?></td>     
        <td><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></td>
    <?php elseif ($registration->participation === 1) : ?>
    <tr class="success">
        <td><?php echo ++$i ?></td>
        <td><?php echo $registration->charactername ?></td>
        <td><?php echo $registration->comment ?></td>     
        <td><span class="glyphicon glyphicon-ok" aria-hidden="true"></td>        
    <?php elseif ($registration->participation === 2) : ?>
    <tr class="warning">
        <td><?php echo ++$i ?></td>
        <td><?php echo $registration->charactername ?></td>
        <td><?php echo $registration->comment ?></td> 
        <td></td>
    <?php else : ?>
    <tr>
        <td><?php echo ++$i ?></td>
        <td><?php echo $registration->charactername ?></td>
        <td><?php echo $registration->comment ?></td> 
        <td></td>        
    <?php endif; ?>
    </tr>
<?php endforeach;?>   
    </tbody>
    
    <tfoot>
        <tr>
            <td colspan="4">&nbsp;</td>
        </tr>
    </tfoot>
</table>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == 'registration') : ?>
<div class="well bs-component col-md-4 col-lg-4">
    <legend>Raidanmeldung</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <input type="hidden" name="raidid" value="<?php echo \Base::instance()->get('raidinfo')->id ?>" hidden>

        <div class="form-group">
            <label for="datetime" class="control-label">Datum</label>

            <input type="datetime" id="datetime" name="datetime" value="<?php echo date("d.m.Y H:i", strtotime(\Base::instance()->get('raidinfo')->datetime)) ?>" class="form-control" readonly>
        </div>        
        
         <div class="form-group">    
            <label class="control-label">Character</label>

            <?php foreach (\Base::instance()->get('characterlist') as $character) : ?>
            <div class="radio">
                <label><input type="radio" name="characterid" value='<?php echo $character->id ?>'><?php echo $character->name ?></label>
            </div>        
            <?php endforeach ?>
        </div>       

        <div class="form-group">    
            <label class="control-label">Teilnahme</label>

            <div class="radio">
                <label><input type="radio" name="participation" value='1' checked>Ja</label>
            </div>        
            <div class="radio">
                <label><input type="radio" name="participation" value='0' checked>Nein</label>
            </div>  
            <div class="radio">
                <label><input type="radio" name="participation" value='2' checked>Eventuell</label>
            </div> 
        </div>

        <div class="form-group">    
            <label for="text" class="control-label">Bemerkung</label>

            <input type="time" name="text" id="text" placeholder="Einschränkung, Hinweis, etc." class="form-control">   
        </div>        

        <input type="submit" name="submit" class="btn btn-primary" value="Platz reservieren"> 
    </form>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == 'create') : ?>
<div class="well bs-component col-md-4 col-lg-4">
    <legend>Create Raid</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <div class="form-group">
            <label for="raidtypeid" class="control-label">Raid</label>

            <select name="raidtypeid" id="raidtypeid" class="form-control">
            <?php foreach (\Base::instance()->get('raidtypes') as $raidtype):?>
                <option value="<?php echo $raidtype->id ?>">
                    <?php echo $raidtype->name." ".$raidtype->players." (".$raidtype->difficulty.")" ?>
                </option>
            <?php endforeach; ?>    
            </select>
        </div>

        <div class="form-group">     
            <label for="date" class="control-label">Date</label>

            <input type="date" name="date" id="date" placeholder="<?php echo date('d.m.Y'); ?>" class="form-control" value="<?php echo date('d.m.Y'); ?>" required>    
        </div>

        <div class="form-group">
            <label for="time" class="control-label">Time</label>

            <input type="time" name="time" id="time" placeholder="20:00" class="form-control" value="20:00" required>    
        </div>

        <input type="submit" name="submit" class="btn btn-primary" value="Create"> 
    </form>
</div>    
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == 'edit') : ?>
<div class="well bs-component col-md-4 col-lg-4">
    <legend>Edit Raid</legend>
    <form action=""  method="POST" enctype="multipart/form-data">
        
        <input type="hidden" name="id" value="<?php echo \Base::instance()->get('raid')->id ?>">

        <div class="form-group">
            <label for="raidtypeid" class="control-label">Raid</label>
            <?php
            $raid = \Base::instance()->get('raid');
                $raidname = $raid->name." ".$raid->players." (".$raid->difficulty.")";
            ?>

            <input name="raidtypeid" id="raidtypeid" class="form-control" value="<?php echo $raidname ?>" readonly>
        </div>

        <div class="form-group">     
            <label for="date" class="control-label">Date</label>

            <input type="date" name="date" id="date" placeholder="<?php echo date('d.m.Y'); ?>" class="form-control" value="<?php echo date('d.m.Y'); ?>" required>    
        </div>

        <div class="form-group">
            <label for="time" class="control-label">Time</label>

            <input type="time" name="time" id="time" placeholder="20:00" class="form-control" value="20:00" required>    
        </div>

        <input type="submit" name="submit" class="btn btn-primary" value="Edit"> 
    </form>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == 'delete') : ?>
<?php
$raid = \Base::instance()->get('raid');
    $raidname = $raid->name." ".$raid->players." (".$raid->difficulty.")";
?>
<p>Delete Raid <?php echo $raidname ?></p>
<form action=""  method="POST" enctype="multipart/form-data">
    <input type="submit" name="submit" class="btn btn-danger" value="Delete">
    <a class="btn btn-primary" href="/raid/list" role="button">Back</a>
</form>
<?php endif ?>

<?php if (is_array(\Base::instance()->get('SESSION.failedFields'))) : ?>
<script>
    <?php foreach (\Base::instance()->get('SESSION.failedFields') as $fieldname) : ?>
    $("#<?php echo $fieldname ?>").parent().addClass('has-error');
    <?php endforeach; ?>
    <?php \Base::instance()->clear('SESSION.failedFields'); ?>
</script>
<?php endif ?>