<div class="jumbotron">
    <h1>RaidPlaner</h1>
    <?php if (\Base::instance()->get('SESSION.user')) : ?>
    <p>Willkommen beim Raidplaner von Ultima Pars.</p>
    <p>
        <a class="btn btn-primary btn-lg" href="/character/create" role="button">Create Character</a>
        <a class="btn btn-primary btn-lg" href="/raid/list" role="button">List planned Raids</a>
    </p> 
    <?php else : ?>
    <p>Willkommen beim Raidplaner von Ultima Pars. <br>
       Um die Funktionen dieses Raidplaners nutzen zu können, musst du dir einen User-Account erstellen.</p>
    <p><a class="btn btn-primary btn-lg" href="/user/create" role="button">Registrieren</a></p>
    <?php endif ?>
</div>


