<div class="well bs-component col-md-4 col-lg-4">
    <legend>Login</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <div class="form-group">
            <label for="email" class="control-label">EMail</label>

            <input type="email" name="email" id="email" placeholder="user@example.com" class="form-control">
        </div>        

        <div class="form-group">    
            <label for="password" class="control-label">Passwort</label>

            <input type="password" name="password" id="password" placeholder="Passwort" class="form-control">   
        </div>        

        <input type="submit" name="submit" class="btn btn-primary" value="Login"> 
    </form>
</div>