<?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
<div class="alert alert-danger">
    <i class="glyphicon glyphicon-exclamation-sign"></i> <strong>Error!</strong><br>
    <?php 
        echo \Base::instance()->get('SESSION.errormsg');
        \Base::instance()->clear('SESSION.errormsg');
    ?>
</div>
<?php endif ?>
<?php if (\Base::instance()->get('SESSION.successmsg') != "") : ?>
<div class="alert alert-success">
    <i class="glyphicon glyphicon-ok"></i> <strong>OK!</strong><br>
    <?php 
        echo \Base::instance()->get('SESSION.successmsg');
        \Base::instance()->clear('SESSION.successmsg');
    ?>
</div>
<?php endif ?>

<div class="well bs-component col-md-4 col-lg-4">
    <legend>Login</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <div class="form-group">
            <label for="email" class="control-label">EMail</label>

            <input type="email" name="email" id="email" placeholder="user@example.com" class="form-control">
        </div>        

        <div class="form-group">    
            <label for="password" class="control-label">Password</label>

            <input type="password" name="password" id="password" placeholder="Password" class="form-control">   
        </div>        

        <input type="submit" name="submit" class="btn btn-primary" value="Login"> 
    </form>
</div>

<?php if (is_array(\Base::instance()->get('SESSION.failedFields'))) : ?>
<script>
    <?php foreach (\Base::instance()->get('SESSION.failedFields') as $fieldname) : ?>
    $("#<?php echo $fieldname ?>").parent().addClass('has-error');
    <?php endforeach; ?>
    <?php \Base::instance()->clear('SESSION.failedFields'); ?>
</script>
<?php endif ?>