<?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
<div class="alert alert-danger">
    <i class="glyphicon glyphicon-exclamation-sign"></i>
    <?php 
        echo \Base::instance()->get('SESSION.errormsg');
        \Base::instance()->clear('SESSION.errormsg');
    ?>
</div>
<?php endif ?>

<form action=""  method="POST" enctype="multipart/form-data">
    
    <div class="form-group">
        <label for="name">Name</label>    
        <input type="text" name="name" placeholder="Spielername" class="form-control" required>
    </div>        
    
    <div class="form-group">
        <label for="armorclass">Rüstwert</label>    
        <div class="form-control">
            <input type="radio" name="armorclass" value='790' checked>790
            <input type="radio" name="armorclass" value='862'>862
            <input type="radio" name="armorclass" value='934'>934
            <input type="radio" name="armorclass" value='1006'>1006
            <input type="radio" name="armorclass" value='1078'>1078
        </div>
    </div>        
    
    <div class="form-group">
        <label for="email">EMail</label>    
        <input type="email" name="email" placeholder="user@example.com" class="form-control">   
    </div>        
    
    <input type="submit" name="submit" class="btn btn-primary" value="Spieler registrieren"> 
</form>

<script>
    <?php foreach (\Base::instance()->get('SESSION.failedFields') as $fieldname) : ?>
    $("input[name='<?php echo $fieldname ?>']").parent().addClass('has-error');
    <?php endforeach; ?>
    <?php \Base::instance()->clear('SESSION.failedFields');
</script>
    