<?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
<div class="alert alert-danger">
    <i class="glyphicon glyphicon-exclamation-sign"></i><strong>Error!</strong><br>
    <?php 
        echo \Base::instance()->get('SESSION.errormsg');
        \Base::instance()->clear('SESSION.errormsg');
    ?>
</div>
<?php endif ?>

<div class="well bs-component col-md-4 col-lg-4">
    <legend>Spieler registrieren</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <div class="form-group">
            <label for="name" class="control-label">Name</label> 

            <input type="text" name="name" id="name" placeholder="Spielername" class="form-control" required>        
        </div>        

        <div class="form-group">
            <label class="control-label">Rüstwert</label>    

            <div class="radio">
                <label><input type="radio" name="armorclass" value='790' checked>790</label>
            </div>
            <div class="radio">
                <label><input type="radio" name="armorclass" value='862'>862</label>
            </div>
            <div class="radio">            
                <label><input type="radio" name="armorclass" value='934'>934</label>
            </div>
            <div class="radio">            
                <label><input type="radio" name="armorclass" value='1006'>1006</label>
            </div>
            <div class="radio">            
                <label><input type="radio" name="armorclass" value='1078'>1078</label>
            </div>
        </div>        

        <div class="form-group">
            <label for="email" class="control-label">EMail</label> 

            <input type="email" name="email" id="email" placeholder="user@example.com" class="form-control"> 
        </div>        

        <input type="submit" name="submit" class="btn btn-primary" value="Spieler registrieren"> 
    </form>
</div>

<?php if (is_array(\Base::instance()->get('SESSION.failedFields'))) : ?>
<script>
    <?php foreach (\Base::instance()->get('SESSION.failedFields') as $fieldname) : ?>
    $("#<?php echo $fieldname ?>").parent().addClass('has-error');
    <?php endforeach; ?>
    <?php \Base::instance()->clear('SESSION.failedFields'); ?>
</script>
<?php endif ?>
    