<?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
<div class="alert alert-danger">
    <i class="glyphicon glyphicon-exclamation-sign"></i><strong>Error!</strong><br>
    <?php 
        echo \Base::instance()->get('SESSION.errormsg');
        \Base::instance()->clear('SESSION.errormsg');
    ?>
</div>
<?php endif ?>

<div class="well bs-component col-md-4 col-lg-4">
    <legend>Raidanmeldung</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <input type="hidden" name="playerid" value="<?php echo \Base::instance()->get('playerid') ?>" hidden>    
        <input type="hidden" name="raidid" value="<?php echo \Base::instance()->get('raidid') ?>" hidden>

        <div class="form-group">
            <label for="datetime" class="control-label">Datum</label>

            <input type="datetime" id="datetime" name="datetime" value="<?php echo date("d.m.Y H:i", strtotime(\Base::instance()->get('datetime'))) ?>" class="form-control" readonly>
        </div>        

        <div class="form-group">    
            <label class="control-label">Teilnahme</label>

            <div class="radio">
                <label><input type="radio" name="participation" value='1' checked>Ja</label>
            </div>        
            <div class="radio">
                <label><input type="radio" name="participation" value='0' checked>Nein</label>
            </div>  
            <div class="radio">
                <label><input type="radio" name="participation" value='2' checked>Eventuell</label>
            </div> 
        </div>

        <div class="form-group">    
            <label for="text" class="control-label">Bemerkung</label>

            <input type="time" name="text" id="text" placeholder="Einschränkung, Hinweis, etc." class="form-control">   
        </div>        

        <input type="submit" name="submit" class="btn btn-primary" value="Platz reservieren"> 
    </form>
</div>

<?php if (is_array(\Base::instance()->get('SESSION.failedFields'))) : ?>
<script>
    <?php foreach (\Base::instance()->get('SESSION.failedFields') as $fieldname) : ?>
    $("#<?php echo $fieldname ?>").parent().addClass('has-error');
    <?php endforeach; ?>
    <?php \Base::instance()->clear('SESSION.failedFields'); ?>
</script>
<?php endif ?>