<?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
<div class="alert alert-danger">
    <i class="glyphicon glyphicon-exclamation-sign"></i>
    <?php 
        echo \Base::instance()->get('SESSION.errormsg');
        \Base::instance()->clear('SESSION.errormsg');
    ?>
</div>
<?php endif ?>

<form action=""  method="POST" enctype="multipart/form-data">
    
    <input type="hidden" name="playerid" value="<?php echo \Base::instance()->get('playerid') ?>" hidden>    
    <input type="hidden" name="raidid" value="<?php echo \Base::instance()->get('raidid') ?>" hidden>
    
    <div class="form-group">
        <label for="datetime">Datum</label>
        <input type="datetime" name="datetime" value="<?php echo \Base::instance()->get('datetime') ?>" class="form-control" disabled>
    </div>        
    
    <div class="form-group">    
        <label for="participation">Teilnahme</label>
        <div class="form-control">
            <input type="radio" name="participation" value='1' checked>Ja
            <input type="radio" name="participation" value='0'>Nein
            <input type="radio" name="participation" value='2'>Eventuell
        </div>
    </div>
    
    <div class="form-group">    
        <label for="text">Bemerkung</label>
        <input type="time" name="text" placeholder="Einschränkung, Hinweis, etc." class="form-control">   
    </div>        
    
    <input type="submit" name="submit" class="btn btn-primary" value="Platz reservieren"> 
</form>