<?php if (\Base::instance()->get('SESSION.errormsg') != "") : ?>
<div class="alert alert-danger">
    <i class="glyphicon glyphicon-exclamation-sign"></i><strong>Error!</strong><br>
    <?php 
        echo \Base::instance()->get('SESSION.errormsg');
        \Base::instance()->clear('SESSION.errormsg');
    ?>
</div>
<?php endif ?>
<?php if (\Base::instance()->get('SESSION.successmsg') != "") : ?>
<div class="alert alert-success">
    <i class="glyphicon glyphicon-ok"></i> <strong>OK!</strong><br>
    <?php 
        echo \Base::instance()->get('SESSION.successmsg');
        \Base::instance()->clear('SESSION.successmsg');
    ?>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == "list") : ?>
<div class="table-responsive">
<table class="table table-bordered table-hover table-condensed table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Charactertype</th>
            <th>Armorclass</th>
            <th></th>
        </tr>
    </thead>
    
    <tbody>
<?php foreach (\Base::instance()->get('characters') as $character):?>
    <tr>
        <td><?php echo $character->name ?></td>
        <td><?php echo $character->charactertype ?></td>
        <td><?php echo $character->armorclass ?></td>     
        <td>
            <a class="btn btn-warning btn-sm" href="/character/edit/<?php echo $character->id ?>" role="button">
                <i class="glyphicon glyphicon-pencil"></i> Edit
            </a>
            <a class="btn btn-danger btn-sm" href="/character/delete/<?php echo $character->id ?>" role="button">
                <i class="glyphicon glyphicon-remove"></i> Delete
            </a>
        </td>      
    </tr>
<?php endforeach;?>   
    </tbody>
    
    <tfoot>
        <tr>
            <td colspan="6">&nbsp;</td>
        </tr>
    </tfoot>
</table>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == "create") : ?>
<div class="well bs-component col-md-4 col-lg-4">
    <legend>Character registrieren</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <div class="form-group">
            <label for="name" class="control-label">Name</label> 

            <input type="text" name="name" id="name" placeholder="Charactename" class="form-control" required>        
        </div>    
        
        <div class="form-group">
            <label class="control-label">Klasse</label>    

            <select name="charactertypeid" class="form-control">
                <?php foreach (\Base::instance()->get('characterTypes') as $class) :?>
                <option value='<?php echo $class->id ?>'><?php echo $class->name ?></option>
                <?php endforeach; ?>
            </select>
        </div>          

        <div class="form-group">
            <label class="control-label">Rüstwert</label>    

            <?php foreach(\Base::instance()->get('armorClasses') as $armorclass) : ?>
            <div class="radio">
                <label><input type="radio" name="armorclass" value='<?php echo $armorclass->armorclass ?>'><?php echo $armorclass->armorclass ?></label>
            </div>
            <?php endforeach ?>
        </div>        

        <input type="submit" name="submit" class="btn btn-primary" value="Register Character"> 
    </form>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == "edit") : ?>
<div class="well bs-component col-md-4 col-lg-4">
    <legend>Edit Character</legend>
    <form action=""  method="POST" enctype="multipart/form-data">

        <input type="hidden" name="id" value="<?php echo \Base::instance()->get('character')->id ?>">
        
        <div class="form-group">
            <label for="name" class="control-label">Name</label> 

            <input type="text" name="name" id="name" value="<?php echo \Base::instance()->get('character')->name ?>" class="form-control" readonly>        
        </div>    
        
        <div class="form-group">
            <label class="control-label">Klasse</label>    

            <input type="text" name="class" id="name" value="<?php echo \Base::instance()->get('character')->charactertype ?>" class="form-control" readonly> 
        </div>          

        <div class="form-group">
            <label class="control-label">Rüstwert</label>    

            <?php foreach(\Base::instance()->get('armorClasses') as $armorclass) : ?>
            <div class="radio">
                <label><input type="radio" name="armorclass" value='<?php echo $armorclass->armorclass ?>'><?php echo $armorclass->armorclass ?></label>
            </div>
            <?php endforeach ?>
        </div>        

        <input type="submit" name="submit" class="btn btn-primary" value="Submit"> 
    </form>
</div>
<?php endif ?>

<?php if (\Base::instance()->get('PARAMS.action') == "delete") : ?>
<p>Delete Character <?php echo \Base::instance()->get('character')->name ?>?</p>
<form action=""  method="POST" enctype="multipart/form-data">
    <input type="submit" name="submit" class="btn btn-danger" value="Delete">
    <a class="btn btn-primary" href="/character/list" role="button">Back</a>
</form>

<?php endif ?>

<?php if (is_array(\Base::instance()->get('SESSION.failedFields'))) : ?>
<script>
    <?php foreach (\Base::instance()->get('SESSION.failedFields') as $fieldname) : ?>
    $("#<?php echo $fieldname ?>").parent().addClass('has-error');
    <?php endforeach; ?>
    <?php \Base::instance()->clear('SESSION.failedFields'); ?>
</script>
<?php endif ?>
    