<?php $f3 = \Base::instance() ?>

<html>
    <body>
        Hallo!<br>
        <br>
        Willkommen beim RaidPlaner von <?php echo $f3->get('GUILDNAME') ?>!<br>
        <br>
        Klicke auf diesen Link um deinen Benutzer zu aktivieren<br>
        <a href="<?php echo $f3->get('HOSTBASEURL') ?>/user/mailvalidation/<?php echo $f3->get('newuser')->id . "/" . $f3->get('newuser')->mailvalidation ?>">
            <?php echo $f3->get('HOSTBASEURL') ?>/user/mailvalidation/<?php echo $f3->get('newuser')->id . "/" . $f3->get('newuser')->mailvalidation ?>
        </a><br>
        <br>
        <?php echo $f3->get('GUILDNAME') ?>
    </body>
</html>
    
